// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKAMmnxvhrp3L02kHc_QNZfvEXdhwn_eI',
    appId: '1:500044140902:web:ab9528aba78ca1f6e2b8a7',
    messagingSenderId: '500044140902',
    projectId: 'kelompok6apb',
    authDomain: 'kelompok6apb.firebaseapp.com',
    storageBucket: 'kelompok6apb.appspot.com',
    measurementId: 'G-9MQHLNM4SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrnFZxzNXQpGs2-RR8avNPF5kQOwFNIVw',
    appId: '1:500044140902:android:61ba707cf11f45f4e2b8a7',
    messagingSenderId: '500044140902',
    projectId: 'kelompok6apb',
    storageBucket: 'kelompok6apb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB0PZEj-M-x4RS9A3hD6KjA8hADpSJYhw',
    appId: '1:500044140902:ios:84c655d68a2160d5e2b8a7',
    messagingSenderId: '500044140902',
    projectId: 'kelompok6apb',
    storageBucket: 'kelompok6apb.appspot.com',
    iosClientId: '500044140902-588iltrgfi8p5sadvqqp8f83msfnnmkh.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitSpeedCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB0PZEj-M-x4RS9A3hD6KjA8hADpSJYhw',
    appId: '1:500044140902:ios:84c655d68a2160d5e2b8a7',
    messagingSenderId: '500044140902',
    projectId: 'kelompok6apb',
    storageBucket: 'kelompok6apb.appspot.com',
    iosClientId: '500044140902-588iltrgfi8p5sadvqqp8f83msfnnmkh.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitSpeedCode',
  );
}
